spring:
  application:
    name: startproject
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  exchange: spring-boot-exchange
  routing:
    toB: rk.b
  queue:
    b: queue.b